# Generated by Django 3.2.20 on 2023-09-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
